config/routes.rb
Jobsite::Application.routes.draw do
  resources :listings

  devise_for :admins

  devise_for :users

  match 'search' => 'listings#search'

  root :to => "pages#home"

end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/listing.rb
class Listing
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :position
  field :company
  field :description
  field :ending, :type => Date, :default => lambda { Date.today + 1.month }
  field :premium, :type => Boolean, :default => false
  
  field :city
  field :country
  
  # filter options 1-5 
  field :exotic_score, :type => Integer, :default => 1
  field :entrepenural_score, :type => Integer, :default => 1
  field :social_score, :type => Integer, :default => 1
  field :financial_score, :type => Integer, :default => 1

  referenced_in :user
  
  validates_presence_of :title, :position, :company, :city, :country
      
  def to_s
    title
  end
  
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :validatable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable


    
  references_many :listings

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < InheritedResources::Base

  before_filter :authenticate_user!, :except => :search
  
  def search
    criteria = Listing.criteria
    
    unless params[:q].blank?
      criteria = criteria.where(:title => /#{params[:q]}/i)
    end

    scores = params.select{|k,v| k.split('_')[1] == 'score'}   
    scores.each{ |k,v| 
      criteria = criteria.where(:"#{k}".gte =>  v.to_i)
    }
    
    listings = criteria.desc(:created_at)
    
    render :json => listings, :content_type => 'application/json'
  end

  protected
  def begin_of_association_chain
    @current_user
  end
  
  def collection
    @listings ||= end_of_association_chain.desc(:created_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @listings = Listing.desc(:created_at).limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def r(str)
    return unless str
    ::RDiscount.new(str,:filter_styles, :autolink).to_html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_form_errors.html.erb
<% if form_errors.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(form_errors.errors.count, "error") %> prohibited this form from being saved:</h2>

		<ul>
		<% form_errors.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobsite</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <div id="container">
    <header>
    <ul>
    <li><%= link_to "Home", root_path %>
    
    <% if user_signed_in? -%>
    <li><%= current_user %> </li>
    
    <li><%= link_to 'Job Listings', listings_path %></li>
    
    <li><%= link_to "Sign Out", destroy_user_session_path %></li>
    <% elsif admin_signed_in? -%>

    <li>moderate a job</li>
    <li><%= link_to "Sign Out", destroy_admin_session_path %></li>
    <% else -%>

    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>     
    <% end -%>
    </ul>
    </header>
    
    <div id="main">
    <%= yield %>
    </div>
    
    <footer>

    </footer>
  </div> <!--! end of #container -->



</body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= render :partial => 'layouts/form_errors', :object => @listing %>
  <%= f.input :title %>
  <%= f.input :position %>
  <%= f.input :company %>

  <%= f.input :city %>
  <%= f.input :country, :priority => [:GB, :US] %>
  
  <%= f.input :description, :as => :text %>
  
  <%= f.input :ending, :as => :date %>
  
  <%= f.button :submit %>
<% end %>

app/views/listings/_listing.html.erb
<li>

<%= link_to listing, listing %> <br/>

<%= listing.position %> - <%= listing.company %> (<%= listing.city %>, <%= listing.country %>)

</li>

app/views/listings/index.html.erb
<h1>Job Listings</h1>

<p><%= link_to "post a job", new_listing_path %></p>

<ul>
<%= render @listings %>
</ul>

app/views/listings/new.html.erb
<h1>New Job</h1>
<%= render 'form' %>

app/views/listings/show.html.erb
<h1><%= @listing %></h1>
<p><%= @listing.position %> - <%= @listing.company %> (<%= @listing.city %>, <%= @listing.country %>)</p>
<p><%= r @listing.description %>

app/views/pages/home.html.erb
<h1>Basic Jobsite</h1>

<p>Search
<%= form_tag "/search", :method => :get, "data-remote" => "true", :id => "job-search" do %>
<%= text_field_tag :q %>
<%= label_tag 'entrepenural_score' %>
<%= select_tag 'entrepenural_score', options_for_select((1..5)) %>
<%= label_tag 'exotic_score' %>
<%= select_tag 'exotic_score', options_for_select((1..5)) %>
<%= label_tag 'financial_score' %>
<%= select_tag 'financial_score', options_for_select((1..5)) %>
<%= label_tag 'social_score' %>
<%= select_tag 'social_score', options_for_select((1..5)) %>
<% end %>
</p>
<hr />
<ul id='jobs'>
<%= render @listings %>
</ul>

<script id="listings-template" type="text/x-handlebars-template">
  {{#each listings}}

  <li>

   <a href="/listings/{{_id}}">{{title}}</a> <br/>

   {{position }} - {{ company }} ({{ city }}, {{ country }})

  </li>
  {{/each}}
</script>